# permissions for end users to view sensors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensor-viewer-role
rules:
- apiGroups:
  - eventrigger.eventrigger.com
  resources:
  - sensors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventrigger.eventrigger.com
  resources:
  - sensors/status
  verbs:
  - get
